### ISSUE TITLE
Rename all record functions

### ISSUE THREAD

**Issue by dm-gh** [cmc-haskell-2018/straminata#22]
Fro example 
```haskell
Object { name :: String -- ^ Unique object identifier.
       , hitbox :: Hitbox -- ^ Object hitbox
       , velocity :: Vector -- ^ X and Y velocity components.
       }
```
should be 
```haskell
Object { name' :: String -- ^ Unique object identifier.
       , hitbox' :: Hitbox -- ^ Object hitbox
       , velocity' :: Vector -- ^ X and Y velocity components.
       }
```

**Comment by fizruk** [comment]
Please avoid unnecessarily using primes in variable names:
- it's very easy to mix `name` with `name'` in the code, and if they have the same type (or can unify to the same type) it might result in a broken logic;
- prime is normally used to denote strict version of a function (as opposed to lazy), for instance `foldl'` is a strict version of `foldl`.

In Haskell field names live in module namespace, so you can easily get name clashes. Because of that it's common to prefix all field names. For instance:

```haskell
data Object = Object
  { objectName :: String
  , objectHitBox :: HitBox
  , objectVelocity :: Vector
  }
```

If in the future you would like to different means to access fields (e.g. lenses or custom functions), you could also prefix field names with an underscore (`_`) like this:

```haskell
data Object = Object
  { _objectName :: String
  , _objectHitBox :: HitBox
  , _objectVelocity :: Vector
  }
```

**Comment by alois9866** [comment]
(Lenses)[https://hackage.haskell.org/package/lens]

**Comment by alois9866** [comment]
Resolves automatically.
